### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by willirath** [ESM-VFC/xoak#2]
- [x] set up package structure (with poetry?)
- [x] add from [gist](https://nbviewer.jupyter.org/gist/benbovy/adcb7d3b14d22014444a2c57efb30696)
- [x] set up docs (possible with poetry?)
- [x] set up CI
- [x] capture the essence of #1 in a design doc and store it in the repo
- [x] readthedocs?

**Comment by benbovy** [comment]
> capture the essence of #1 in a design doc and store it in the repo

Unless you want to go ahead with this, I'll try to work on it next week.

I'll put a brief overview of data partitioning trees, a topic that is much more vast than I thought as I'm digging into it. That's exciting!

**Comment by willirath** [comment]
> > capture the essence of #1 in a design doc and store it in the repo
> 
> Unless you want to go ahead with this, I'll try to work on it next week.

I'll work on CI and maybe add some more tests or some basic structure for the docs.

**Comment by benbovy** [comment]
Done in #3, #7, #22, #24...
